version: '3.9'

services:
  postgres:
    container_name: discordclone
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_SOURCE}:${DATABASE_SOURCE}
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}